
language:
  - node_js
node_js:
  - "6"
services:
  - postgresql

before_script:
  - psql -c 'create database chuksrecipes;' -U postgres
  - psql -c 'create database recipetest;' -U postgres
  - sequelize db:migrate
  - npm install -g codecov

env:
  global:
    - export NODE_ENV=test

after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  - npm run coverage
