
language: node_js
node_js:
- "6"
services:
- postgresql

before_script:
  - psql -c 'create database chuks-recipes;' -U postgres
  - sequelize db:migrate

env:
    
script:
  - npm test
  - npm install
  - npm run coverage
  
after_success: 'npm run coveralls'