apiVersion: v1
kind: Service
metadata:
  #Service name
  name: more-recipes
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-server
  selector:
    app: more-recipes
